#ifndef __FONTS_H
#define __FONTS_H

/*�������΢���ź�24 (32x41) */
#define MAX_HEIGHT_FONT         41
#define MAX_WIDTH_FONT          32
#define OFFSET_BITMAP           

#ifdef __cplusplus
 extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

//ASCII
typedef struct _tFont
{    
  const uint8_t *table;
  uint16_t Width;
  uint16_t Height;
  
} sFONT;


//GB2312
typedef struct                                          // ������ģ���ݽṹ
{
  unsigned char index[2];                               // ������������
  const char matrix[MAX_HEIGHT_FONT*MAX_WIDTH_FONT/8];  // ����������
}CH_CN;


typedef struct
{
  const CH_CN *table;
  uint16_t size;
  uint16_t ASCII_Width;
  uint16_t Width;
  uint16_t Height;

}cFONT;

// Proportional ASCII font (0x20..0x7E). Unlike sFONT (fixed Width), each glyph
// has its own advance width: `widths[c-' ']` px, and its bitmap starts at byte
// `offsets[c-' ']` in `table` (rows top->bottom, ceil(width/8) bytes/row, bits
// MSB-first). Rendered by Paint_DrawString_P() / Paint_DrawChar_P().
typedef struct _pFont
{
  const uint8_t  *table;
  const uint16_t *offsets;
  const uint8_t  *widths;
  uint16_t        Height;
} pFONT;

extern sFONT Font24;
extern sFONT Font20;
extern sFONT Font16;
extern sFONT Font12;
extern sFONT Font8;

extern cFONT Font12CN;
extern cFONT Font24CN;

// Proportional Poppins faces (generated by tools/gen_font.py).
extern pFONT PoppinsSB24;   // name (SemiBold)
extern pFONT PoppinsMd20;   // headings (Medium)
extern pFONT PoppinsMd16;   // body / labels (Medium)


//�ֿ��ļ�
extern const CH_CN Font12CN_Table[];
#ifdef __cplusplus
}
#endif
  
#endif /* __FONTS_H */
 

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
