#!/usr/bin/env python3
"""Rasterize a TTF into a proportional 1-bit `pFONT` C table for the ePaper GUI.

Emits a .cpp defining `<inst>_table` / `<inst>_offsets` / `<inst>_widths` arrays
plus the `pFONT <inst>` instance consumed by Paint_DrawString_P() in
GUI_Paint.cpp. ASCII 0x20..0x7E only (matches the legacy mono fonts).

Glyph layout matches the mono fonts' reader: each glyph is ceil(w/8)*Height
bytes, rows top->bottom, bits MSB-first (bit 7 = leftmost pixel). Glyphs are
proportional: `widths[i]` is the per-glyph advance and the bitmap is that wide.

Usage (run from this dir, see regen.sh):
  python gen_font.py --ttf Poppins-SemiBold.ttf --size 24 \
      --inst PoppinsSB24 --out ../poppins_sb24.cpp [--preview prev.png]
"""
import argparse
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E          # ' ' .. '~'
THRESHOLD = 127                   # >= -> set pixel


def em_for_cell_height(ttf, target):
    """Pick the em pixel size whose ascent+descent ~= target cell height, so a
    `--size 24` font lands ~24px tall like the legacy Font24 it replaces."""
    probe = ImageFont.truetype(ttf, 200)
    asc, desc = probe.getmetrics()
    em = max(1, round(target * 200 / (asc + desc)))
    return ImageFont.truetype(ttf, em)


def render_glyph(font, ch, cell_h):
    """Return (advance_width, packed_bytes) for one glyph."""
    adv = max(1, round(font.getlength(ch)))
    img = Image.new("L", (adv, cell_h), 0)
    draw = ImageDraw.Draw(img)
    # anchor 'la' = pen origin at (x=left, y=ascender top); baseline at ascent,
    # so every glyph shares one baseline and the left side bearing is included.
    draw.text((0, 0), ch, fill=255, font=font, anchor="la")
    px = img.load()

    row_bytes = (adv + 7) // 8
    data = bytearray()
    for y in range(cell_h):
        for b in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < adv and px[x, y] >= THRESHOLD:
                    byte |= 0x80 >> bit
            data.append(byte)
    return adv, bytes(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="target cell height px")
    ap.add_argument("--inst", required=True, help="pFONT instance name, e.g. PoppinsSB24")
    ap.add_argument("--out", required=True, help="output .cpp path")
    ap.add_argument("--preview", help="optional PNG preview of the packed bytes")
    args = ap.parse_args()

    font = em_for_cell_height(args.ttf, args.size)
    asc, desc = font.getmetrics()
    cell_h = asc + desc

    table = bytearray()
    offsets, widths, glyphs = [], [], []
    for code in range(FIRST, LAST + 1):
        adv, data = render_glyph(font, chr(code), cell_h)
        offsets.append(len(table))
        widths.append(adv)
        glyphs.append((adv, data))
        table.extend(data)

    lo = args.inst.lower()
    with open(args.out, "w") as f:
        f.write(f'// Generated by tools/gen_font.py from {args.ttf} '
                f'(cell {cell_h}px). Do not edit by hand.\n')
        f.write('#include "fonts.h"\n\n')

        f.write(f"static const uint8_t {lo}_table[] = {{\n")
        for code, (adv, data) in zip(range(FIRST, LAST + 1), glyphs):
            f.write(f"  /* '{chr(code)}' (w={adv}) */ ")
            f.write(", ".join(f"0x{b:02x}" for b in data))
            f.write(",\n")
        f.write("};\n\n")

        f.write(f"static const uint16_t {lo}_offsets[] = {{\n  ")
        f.write(", ".join(str(o) for o in offsets))
        f.write("\n};\n\n")

        f.write(f"static const uint8_t {lo}_widths[] = {{\n  ")
        f.write(", ".join(str(w) for w in widths))
        f.write("\n};\n\n")

        f.write(f"pFONT {args.inst} = {{\n")
        f.write(f"  {lo}_table,\n  {lo}_offsets,\n  {lo}_widths,\n  {cell_h},\n}};\n")

    print(f"{args.inst}: cell {cell_h}px, {len(table)} table bytes -> {args.out}")

    if args.preview:
        sample = "Hello Wjpqg 0123 fi"
        total = sum(widths[ord(c) - FIRST] for c in sample) + 8
        canvas = Image.new("L", (total, cell_h + 4), 255)
        cpx = canvas.load()
        x = 4
        for c in sample:
            adv, data = glyphs[ord(c) - FIRST]
            row_bytes = (adv + 7) // 8
            for y in range(cell_h):
                for px in range(adv):
                    byte = data[y * row_bytes + (px >> 3)]
                    if byte & (0x80 >> (px & 7)):
                        cpx[x + px, y + 2] = 0
            x += adv
        canvas.save(args.preview)
        print(f"  preview -> {args.preview}")


if __name__ == "__main__":
    main()
